[project]
name = "fbtools"
version = "0.1.0"
description = "A tool for facebook automation for both official and unofficial."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
]
